{{- if .Values.consul.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-consul
  labels:
    app: {{ .Release.Name }}-consul
spec:
  replicas: {{ .Values.consul.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-consul
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-consul
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: nodeports-open
      #               operator: In
      #               values:
      #                 - "true"
      containers:
        - name: consul
          image: "{{ .Values.consul.image.repository }}:{{ .Values.consul.image.tag }}"
          imagePullPolicy: {{ .Values.consul.image.pullPolicy }}
          args:
            - "agent"
            - "-dev"
            - "-client=0.0.0.0"
          ports:
            - name: http
              containerPort: {{ .Values.consul.service.port }}
            - name: dns
              containerPort: 8600
          resources:
            {{- toYaml .Values.consul.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-consul
  labels:
    app: {{ .Release.Name }}-consul
spec:
  type: {{ .Values.consul.service.type }}
  ports:
    - name: http
      port: {{ .Values.consul.service.port }}
      targetPort: http
    - name: dns
      port: 8600
      targetPort: dns
  selector:
    app: {{ .Release.Name }}-consul
{{- end }}
