{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  labels:
    app: {{ .Release.Name }}-nginx
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log notice;
    pid /var/run/nginx.pid;
    events {
        worker_connections 1024;
    }
    http {
        log_format basic '$remote_addr [$time_local] '
                         '$status $body_bytes_sent '
                         '$request_time "$upstream_addr"';

        access_log /dev/stdout basic;

        resolver kube-dns.kube-system.svc.cluster.local valid=10s;

        map $remote_addr $consul_backend {
            default {{ .Release.Name }}-consul.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.consul.service.port }};
        }
        map $remote_addr $gateway_backend {
            default {{ .Release.Name }}-gateway-service.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.gateway.service.port }};
        }
        map $remote_addr $app_backend {
            default {{ .Release.Name }}-frontend.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.frontend.service.port }};
        }

        server {
            listen 80;

            location ~ ^/(consul|ui|v1)(/.*)?$ {
              # Strip /consul prefix if present, otherwise leave path unchanged
              rewrite ^/consul(?:/(.*))?$ /$1 break;
              
              proxy_pass http://$consul_backend;
              proxy_redirect / /consul/;
            }

            location / {
              proxy_pass http://$app_backend;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: {{ .Release.Name }}-nginx
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: {{ .Release.Name }}-nginx
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-nginx
{{- end }}
